apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apricot-ik-am
  namespace: cert-manager
spec:
  dnsNames:
  - "apricot.ik.am"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: apricot-ik-am