#@ load("@ytt:data", "data")
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-auth
  namespace: default
spec:
  plugin:
    oidc-auth:
      Provider:
        ClientId: #@ data.values.oidc_client_id
        ClientSecret: #@ data.values.oidc_client_secret
        Url: #@ data.values.oidc_provider_url
      Scopes:
      - openid
      - profile
      - email
