#@ load("@ytt:data", "data")
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: api-token
spec:
  plugin:
    api-token:
      bearerHeader: true
      bearerHeaderName: Authorization
      tokens:
      - foo
      - bar