#@ load("@ytt:data", "data")
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-auth
  namespace: default
spec:
  plugin:
    oidc-auth:
      Secret: #@ data.values.secret
      forceHTTPS: "true"
      Provider:
        ClientId: #@ data.values.keycloak.client_id
        ClientSecret: #@ data.values.keycloak.client_secret
        Url: #@ data.values.keycloak.provider_url
        UseClaimsFromUserInfo: "true"
      Scopes:
      - openid
      - profile
      - email