apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: entry-api-tls
  namespace: blog
spec:
  dnsNames:
  - entry-api.ik.am
  - api.ik.am
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-ik-am
  secretName: entry-api-tls

