#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: entry-api-config
  namespace: blog
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  spring-datasource-url: #@ data.values.spring_datasource_url
  spring-datasource-username: #@ data.values.spring_datasource_username
  spring-data-redis-url: #@ data.values.spring_data_redis_url
  github-access-token: #@ data.values.github_access_token
  github-webhook-secret: #@ data.values.github_webhook_secret
  github-access-token-en: #@ data.values.github_access_token_en
  github-webhook-secret-en: #@ data.values.github_webhook_secret_en
  github-access-token-note: #@ data.values.github_access_token_note
  github-webhook-secret-note: #@ data.values.github_webhook_secret_note
  admin-password: #@ data.values.admin_password
  users-0: #@ data.values.users[0]
  users-1: #@ data.values.users[1]
  users-2: #@ data.values.users[2]
  openai-url: #@ data.values.openai_url
  openai-chat-model: #@ data.values.openai_chat_model
  openai-apikey: #@ data.values.openai_apikey
  s3-url: #@ data.values.s3_url
  s3-access-key: #@ data.values.s3_access_key
  s3-secret-key: #@ data.values.s3_secret_key
  s3-bucket-name: #@ data.values.s3_bucket_name