#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: regsecret
  namespace: app-install
type: kubernetes.io/dockerconfigjson
stringData:
  #@yaml/text-templated-strings
  .dockerconfigjson: |
    {
      "auths": {
        "(@= data.values.registry_1_url @)": {
          "username": "(@= data.values.registry_1_username @)",
          "password": "(@= data.values.registry_1_password @)"
        },
        "(@= data.values.registry_2_url @)": {
          "username": "(@= data.values.registry_2_username @)",
          "password": "(@= data.values.registry_2_password @)"
        }
      }
    }