apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dorian-ik-am
  namespace: cert-manager
spec:
  dnsNames:
    - "*.dorian.ik.am"
    - "*.apps.dorian.ik.am"
    - "*.system.dorian.ik.am"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: dorian-ik-am-tls