#@ load("@ytt:data", "data")
kind: Secret
apiVersion: v1
metadata:
  name: azuredns-config
  namespace: cert-manager
stringData:
  client-secret: #@ data.values.azure.client_secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: makingx+lemon@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azureDNS:
          clientID: #@ data.values.azure.client_id
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: #@ data.values.azure.subscription_id
          tenantID: #@ data.values.azure.tenant_id
          resourceGroupName: ik-am
          hostedZoneName: ik.am
          environment: AzurePublicCloud