home_global_ip: ENC[AES256_GCM,data:yhz1EmBcfwCSFMDwbeFa,iv:e8pjQT4etaqIzDag/mVNNrRJVbYX+DMsyQgDjVHO+6Y=,tag:L+Z2aLHKxE9muwccKS7rhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSjB6c3hybVc3Q1owcldz
            QW5zRVF6djQydmRNNlNrWFY4R0hoZWIveTAwCnVVVm5hcGVERzV5YkMrQzhYczBr
            YUVVNGN3WUN1bk5jRVRKbm1iYWF6cFEKLS0tIFBwQVN0RWYyVGxpNmV4MDVsRmVL
            OTErbTB2WW8wazRid0hYdHJaVktudVUKDf4kM4JnI2jk9REHvBWtmJ0psuh21XA8
            uYnWe4BG0FyZOi9kwHxnTRcDlKsdYydKYdpb59SfCc9T/mv8Ifs/Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T14:31:50Z"
    mac: ENC[AES256_GCM,data:3rMgX5R9sb4NBia7XxkWMCxvxXL38lmeaEAmTv2260qSbXnFxLwONCxZlLAVPvC1XGYGEEoqkbiFYd3OMZnQU39tk81IZvG8NZPRpFIDQ0EYpnJV5O9PE9vQ+odlixpbmSaaQ0wl6HhE7RqOHLDb1/gO+BVazgSfM5yetbBKF0s=,iv:BH4hxb6F5+VCWCWcaqZrEsDSe0bRmUROHlmHtjfrLUw=,tag:U1YUTGh+8ufMm3rX9L8EKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
