home_global_ip: ENC[AES256_GCM,data:og1qlnqrcwSbKCUFUqg4,iv:H+xax5Dtrn5cKGB4Ah7CQHu7NyF49d4bwUvP8d4B2mw=,tag:e0BUW2Vu8vmiNflqA0MLdQ==,type:str]
cognito:
    client_id: ENC[AES256_GCM,data:8xVOExrkdgpwDMG2JMMqukzT2LNvbAQorQ==,iv:XuBdzGBLYBxgO+5Dir8zEMm+Xq6t8yj7ZjqSAzfwRFQ=,tag:Sc6tRrU/EnnuZn/7oquGpA==,type:str]
    client_secret: ENC[AES256_GCM,data:HA6fBJnNHHAFGTb2oc5mEO9Hkh4DpGWiqg6qCtkIXO3LCBzXcByceg9ptHQR68Sx9iPG,iv:kelqfugI5LrjI9+KUcx7ksy6jjQjJLiGUczMpXkXmM0=,tag:apA6MEh6LPZ4HODCEdcaVQ==,type:str]
    provider_url: ENC[AES256_GCM,data:eg2NHw89dDgeCwlK6bh3+2VZrG68tjzWFthWhx6QWmgE5qS+EeJj8/6Ohju1zSFxmfXZiuWSFNhpS8+HVzf4hdcVsh7baWULKg==,iv:r5oDx5PXBiSDn7V77tEVR7jIAIqMaWzTVWHqHvUeqdg=,tag:NlKKLwcqpntY0HVqeAKZfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTXBMem4zSkNhd2dDRUt3
            dVI2QVFJMlRVYW0zU2JKbWxkckxkc3d4MkNvCkljOG1NYkRQWFdvaFZZSzNIU2gx
            NHhBWHRYeDlYa2piL2oxenM3Y2dkcEEKLS0tIElvaVNCMEN1Zk5yc1RRak8vTFFk
            Vk5vYmFmNTBlaUp4Z3c0amt3c2ZPZGMKQE8HruySowNsE1BqyRn/hCAOLuq2lthI
            pSKZZq5mQPywknkmSZeSh3z7nszTQaaiqsaDU2Yxql9r7hxss1PPTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T02:12:46Z"
    mac: ENC[AES256_GCM,data:MtLVqGDbPqg9k/aks+NPru5HWO39zKmksU5C5bhx8L2xemuAF9ZqOy69PyGlYFF/qxiiaoqP5M0SMIlcmHIYRjlPc/LPPigR0ab9pi0jCtAD8VPvi81kM3xYqffRDY7oI2NNiy+G3aemE4NLnkoTep2d31LHNGRoA/XRiqbWU9g=,iv:DTTNq0JJ6D4hk1++cKGB3be/VfGAkr7uZQt61bgIcLw=,tag:16JB/l2+Ulo61HrvNTElZw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
