apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-blocked-ips
  namespace: haproxy
  annotations:
    kapp.k14s.io/versioned: ""
data:
  blocked-ips.txt: |
    100.31.119.187
    104.197.69.115
    109.149.23.4
    121.127.34.106
    121.91.235.186
    13.219.78.63
    13.38.97.241
    13.56.149.3
    13.79.87.25
    135.237.126.9
    149.50.96.133
    147.185.132.76
    148.153.56.62
    155.248.184.241
    157.143.20.83
    157.143.30.12
    159.65.216.50
    159.89.194.131
    16.145.94.216
    164.90.151.185
    164.92.107.174
    165.227.94.153
    167.71.66.217
    167.94.138.176
    172.192.18.188
    172.237.28.61
    178.128.33.111
    178.22.24.61
    18.177.137.30
    18.182.42.143
    183.182.125.198
    185.12.59.118
    185.126.82.201
    185.16.39.0/24
    185.242.177.0/24
    185.242.226.112
    185.247.137.0/24
    188.166.49.70
    192.159.99.95
    193.142.147.209
    195.178.110.0/24
    195.201.235.93
    198.235.24.0/24
    20.168.113.228
    20.239.59.60
    20.24.218.130
    205.169.39.0/24
    205.210.31.0/24
    20.64.104.5
    20.65.195.96
    208.84.101.0/24
    213.209.157.52
    216.106.189.40
    217.119.139.38
    23.23.43.140
    23.98.91.210
    2.58.56.101
    3.101.132.77
    3.130.96.91
    3.233.59.216
    34.123.170.104
    34.232.63.46
    34.26.246.252
    35.167.205.129
    35.178.0.0/16
    35.237.0.0/16
    37.46.196.22
    3.81.21.209
    3.85.125.1
    40.113.19.56
    4.147.185.30
    4.189.0.0/16
    4.190.202.34
    4.194.85.10
    4.197.60.90
    4.197.217.22
    4.217.217.154
    4.218.20.75
    44.200.137.196
    44.222.79.145
    45.135.193.9
    45.154.98.70
    46.101.48.38
    47.237.86.67
    50.6.229.250
    51.77.218.191
    51.81.245.138
    52.56.158.187
    54.255.185.0/24
    63.35.172.238
    66.240.192.138
    66.249.66.203
    68.218.110.49
    74.7.175.0/24
    74.7.227.0/24
    78.153.140.0/24
    79.100.14.146
    80.239.178.98
    87.236.176.180
    87.236.176.225
    87.236.176.234
    89.46.223.134
    91.232.238.112
    91.239.216.99
    95.214.52.170