#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: translation-config
  namespace: blog
type: Opaque
stringData:
  type: "translation-api"
  openai-api-key: #@ data.values.openai_api_key
  openai-base-url: #@ data.values.openai_base_url
  openai-chat-completions-path: #@ data.values.openai_chat_completions_path
  openai-chat-options-model: #@ data.values.openai_chat_options_model
  github-access-token: #@ data.values.github_access_token
  github-webhook-secret: #@ data.values.github_webhook_secret
