#@ for name in ['synology', 'inlets.gw', 'llama-server.synology', 's3.synology', 'otlp-sink.synology', 'lognroll.synology', 'registry.synology', 'registry-ui.synology']:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #@ name.replace('.', '-')
  namespace: inlets
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    #@ if name != 'synology':
    traefik.ingress.kubernetes.io/router.observability.tracing: "false"
    #@ end
    #@ if name == 'otlp-sink.synology' or name == 'registry-ui.synology' or name == 'lognroll.synology':
    traefik.ingress.kubernetes.io/router.observability.accesslogs: "false"
    #@ end
    #@ if name == 'inlets.gw' or name == 'registry-ui.synology':
    traefik.ingress.kubernetes.io/router.middlewares: traefik-allow-home@kubernetescrd
    #@ end
    #@ if name == 'llama-server.synology':
    traefik.ingress.kubernetes.io/router.middlewares: inlets-api-token@kubernetescrd
    #@ end
spec:
  ingressClassName: traefik
  rules:
  - host: #@ "{}.ik.am".format(name)
    http:
      paths:
      - backend:
          service:
            name: inlets-exit
            port:
              name: inlets-exit
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - #@ "{}.ik.am".format(name)
    secretName: #@ "{}-tls".format(name.replace('.', '-'))
#@ end