#@ for name in ['synology', 'inlets.gw', 'openai.synology', 's3.synology', 'otlp-sink.synology', 'lognroll.synology', 'registry.synology', 'registry-ui.synology']:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #@ name.replace('.', '-')
  namespace: inlets
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-ik-am
    traefik.ingress.kubernetes.io/router.observability.tracing: "false"
spec:
  ingressClassName: traefik
  rules:
  - host: #@ "{}.ik.am".format(name)
    http:
      paths:
      - backend:
          service:
            name: inlets-exit
            port:
              name: inlets-exit
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - #@ "{}.ik.am".format(name)
    secretName: #@ "{}-tls".format(name.replace('.', '-'))
#@ end