apiVersion: v1
kind: Secret
metadata:
  name: regsecret
  namespace: demo
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
    kapp.k14s.io/exists: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K