#@ load("@ytt:data", "data")
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: entry-gemfire-locator
  namespace: blog
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`entry-gemfire-locator.lan.ik.am`)
    middlewares:
    - name: entry-gemfire-locator-auth
    services:
    - name: entry-gemfire-locator
      port: 7070
      scheme: https
      serversTransport: entry-gemfire-locator-transport
  tls:
    secretName: entry-gemfire-locator-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: entry-gemfire-locator-tls
  namespace: blog
spec:
  dnsNames:
  - entry-gemfire-locator.lan.ik.am
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: entry-gemfire-locator-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: entry-gemfire-locator-transport
  namespace: blog
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: entry-gemfire-locator-auth
  namespace: blog
spec:
  basicAuth:
    secret: entry-gemfire-locator-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: entry-gemfire-locator-auth
  namespace: blog
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.locator.username
  password: #@ data.values.locator.password