#@ load("@ytt:data", "data")
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-auth-for-dashbord
  namespace: traefik
spec:
  plugin:
    oidc-auth:
      LogLevel: WARN
      Secret: #@ data.values.secret
      forceHTTPS: "true"
      Provider:
        ClientId: #@ data.values.cognito.client_id
        ClientSecret: #@ data.values.cognito.client_secret
        Url: #@ data.values.cognito.provider_url
      Scopes:
      - openid
      - email