apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: blog-db
  namespace: blog
spec:
  postgresVersion:
    name: postgres-17.5
  storageSize: 1Gi
  highAvailability:
    readReplicas: 2
    enabled: true
  resources:
    data:
      limits:
        cpu: 512m
        memory: 1024Mi
      requests:
        cpu: 512m
        memory: 1024Mi