#@ load("@ytt:data", "data")
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - args:
        - access
        - tcp
        - --hostname
        - #@ data.values.public_hosts.minecraft
        - --url
        - 0.0.0.0:25565
        image: docker.io/cloudflare/cloudflared:latest
        name: cloudflared-minecraft
        ports:
        - name: minecraft
          containerPort: 25565
      - args:
        - access
        - tcp
        - --hostname
        - #@ data.values.public_hosts.mc_vanilla
        - --url
        - 0.0.0.0:35565
        image: docker.io/cloudflare/cloudflared:latest
        name: cloudflared-mc-vanilla
        ports:
        - name: mc-vanilla
          containerPort: 35565
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
  - name: mc-vanilla
    port: 35565
    targetPort: mc-vanilla
  selector:
    app: cloudflared
  type: ClusterIP
