apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: kube-prometheus
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting regsecret"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting regsecret"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: kube-prometheus
      version: 11.5.1
      repository:
        url: oci://registry.maki.lol/bitnamicharts
        secretRef:
          name: regsecret
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/platform/kube-prometheus
  syncPeriod: 24h
  template:
  - helmTemplate:
      name: kube-prometheus
      namespace: kube-prometheus
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - "-"
      - 1/config
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true