apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: traefik
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting cert-manager"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting cluster-issuer"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting cluster-issuer"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: traefik
      version: 37.4.0
      repository:
        url: https://traefik.github.io/charts
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: apricot/platform/traefik
  syncPeriod: 24h
  template:
  - helmTemplate:
      name: traefik
      namespace: traefik
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - "-"
      - 1/config
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true